# Generated by Django 2.2 on 2020-09-06 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='blog.Comment'),
        ),
    ]
